feat: joined utxo tx
bitaccess/coin-payments pull request #201
Opened 2021-05-17 17:07 UTC by dzdidi

Signed-off-by: Denys Bitaccess <denys@bitaccess.co>

## Joined TX

* multi-input tx for btc
* default signer is at index `0`
* change address can be passed as an option

2021-05-17 20:13 UTC, dylanseago requested changes
Overall this is good progress. I need you to address a few concerns which I've commented on. Additionally I see some other significant things that are missing but can be added in separate PRs if you like:
1. `getPayport` needs to accept a new `addressType` option to override the default configured one. This will allow us to support both legacy segwit and native segwit addresses within a single payments config wallet 
2. With above change, this will necessitate inferring the address type in `getPaymentScript` by inspecting the address itself since there could now be potentially a few different addresses for each index. Each address requires a different payment script to successfully spend the utxo
3. Support for multiple `changeAddresses` instead of a single `changeAddress` to avoid compromising privacy when change splitting occurs. The `buildPaymentTx` algorithm can create up to at most `targetUtxoPoolSize` change outputs. Currently all these outputs go back to the single address but with multi input support they can now all be unique

2021-05-17 20:13 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +          u.signer = 0 // use HW by default
Again, can't default to HW because that could result in a malformed transaction. What you could do instead is convert the `from` indices into addresses and create an address -> index mapping. Then use that to lookup each utxo address to find out what index `signer` should be. You can merge https://github.com/go-faast/coin-payments/pull/202 and rebase to get `address` as part of `UtxoInfo`

2021-05-20 16:54 UTC, dylanseago commented
This is good! The logic itself looks correct. But I'm not totally convinced it's been adequately tested. Both e2e tests I see never assert that utxos from two different addresses are actually involved in the transaction. And the amounts being sent are small enough that it very likely is only using a single utxo.

Could you please add another test that just creates and signs (without broadcasting) a transaction from at least two indices and set it up such that the amount being sent must use a utxo from more than one address. This could be added to the e2e.mainnet tests because there are other tests in there doing something similar, but testnet works too. The important part is to just set up some addresses that never actually get spent so the test is reproducible. Let me know if you need an address funded.

2021-06-09 15:28 UTC, dylanseago commented on packages/bitcoin-payments/src/MultisigBitcoinPayments.ts
> +      return AddressType.MultisigSegwitNative
Why not just simplify this to:

```typescript
getAddressType(address: string, index: number): AddressType {
  address = this.standardizeAddress(address)
  for (let addressType of MULTISIG_ADDRESS_TYPES) {
    if (address = this.getAddress(index, addressType)) {
      return addressType
    }
  }
  throw new Error(`Failed to identify address ${address} at index ${index}`)
}
```

This also allows this function to validate that an address really is controlled by a particular index. Which is helpful because it'll help prevent creation of a tx that signs with the wrong private key. For example in the spots where you've used `utxo.signer ?? fromIndex` we don't want to accidentally create a signature using the "default" index for a utxo at some other index that just happened to be missing `signer` field.

Both implementations may work, but the code above is more "robust" and can even be added to bitcoinish payments and used by ALL networks, since it doesn't depend on checking any prefixed constants.

Moving it to bitcoinish would just require either a new config field or abstract method such as `getSupportedAddressTypes` that each class could implement to return what address types it supports. For example each would return:
SingleSigBitcoinPayments: `SINGLESIG_ADDRESS_TYPES`
MultisigBitcoinPayments: `MULTISIG_ADDRESS_TYPES`
BaseBitcoinCashPayments: `[AddressType.Legacy]`

2021-06-09 15:28 UTC, dylanseago commented on packages/bitcoin-payments/src/SinglesigBitcoinPayments.ts
> +    }
See my comment on the multisig implementation as well. This method can be generalized to apply to all bitcoinish implementations so that we can support multi input on ltc/bch/doge as well

2021-06-09 16:32 UTC, dzdidi commented on packages/bitcoin-payments/src/HdBitcoinPayments.ts
> +    if (addressType && addressType !== this.addressType && this.isValidXprv(this.config.hdKey)) {
not if we want to get same address from two payments instantiated with the same xprv but different address types in config. So I suggest to keep it in order to maintain consistency

2021-06-09 16:40 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        address: (changeAddress[i] || changeAddress[(changeAddress.length - 1) % i]),
I don't understand this logic here. If you're trying to account for a situation where not enough change addresses were provided I think you want to use `changeAddress[i % changeAddress.length]` which bounds `i` to the length of `changeAddress` such that it loops back to `0` when `i` exceeds the length

2021-06-09 16:40 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +  private calculateTotalChange(
Can you please call this `allocateChangeUsingWeights` since it does much more than just calculating the total

2021-06-09 16:40 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +  private readjustTxFees(
More descriptive name would be `readjustTxFeeAfterDroppingChangeOutputs`

2021-06-09 16:40 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    }
I see this block is duplicated in createTransaction. Could it be extracted into a helper `resolveChangeAddressOption`

2021-06-09 16:40 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    // sets empty address to some of outputs
What does this comment mean?

2021-06-09 16:40 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    this.logger.debug('createMultiOutputTransaction data', paymentTx)
typo: `createMultiInputTransaction`

2021-06-09 16:40 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +      externalOutputs = this.defaultCallback(tx, skipAddresses)
Can you please give both `txInfoCb` and `defaultCallback` more descriptive names and clarify what exactly they're meant to do? It looks like the essence of it would be determining whether something is a change address. So it would be `filterChangeAddreses: (addresses: string[]) => MaybePromise<string[]>`

Rather than the callback returning the external outputs, all output addresses would be determined first, then passed into the callback to filter out which ones are change. Then the external outputs could be determined by using that list of change outputs.


```
const outputAddresses = tx.vout.map(({ address }) => address)
const changeAddresses = options.filterChangeAddresses
  ? await options.filterChangeAddresses(outputAddresses)
  : [...fromAddresses, ...(options?.changeAddress ?? [])]
const externalOutputs = tx.vout.map(...).filter(({ address }) => !changeAddresses.includes(address))
```

2021-06-10 21:16 UTC, dylanseago reviewed
Regarding my two comments, I've implemented both my suggestions and pushed a commit. It required a bit of a refactor to the multisig data handling methods but this new type should be compatible with future coinjoin features.

I also switched the multisig tests to use the same root xprv as the singlesig tests by deterministically deriving new private keys at arbitrary paths. I funded the addresses and made it easier to increase the number of keypairs or xpubs we may need for future tests.

As far as multisig implementation and tests go things look good on my end. 

Final concern is this failed test. Can you please help me understand what's going on here?
```
  ● e2e testnet › end to end multi-input send

    unfortunate situation

      243 |         forcedUtxos.push(...indexedUtxos[index])
      244 |       } else {
    > 245 |         throw new Error('unfortunate situation')
          |               ^
      246 |       }
      247 |     }
      248 |

      at Object.<anonymous> (test/e2e.testnet.test.ts:245:15)
```

2021-06-15 16:36 UTC, dylanseago requested changes

2021-06-15 16:36 UTC, dylanseago commented on packages/bitcoin-payments/test/e2e.testnet.test.ts
>      const signedTx = await hotWalletPayments.signTransaction(unsignedTx)
This test isn't asserting anything, so aside from simply not erroring it's not really testing much. I've been asking to see a solid test that reliably and reproducibly tests this critical feature and I'm still not convinced this is sufficient.

A good test has defined inputs and expects a known outcome. What I'd like to see is something that creates a transaction with hardcoded utxos, outputs, change addresses, and fee. Asserts that the resulting unsigned transaction uses all the utxos, has all the outputs, and produces expected change output amounts. Then it would sign the transaction, and assert that the hex string exactly matches a known signed transaction that's already been confirmed and manually verified on chain.

By hardcoding everything, a complex transaction that's been manually verified to produce the expected behaviour can be reused and reproduced during every test run. It's critical that this new feature is thoroughly tested because there's so many ways it could go wrong. 

Ideally this transaction should:
- Spend from at least 3 utxos, each from different indices and address types. This ensures that all address types work and spending from multiple indices is working. Bonus if you also include multiple address types using the same indices. (You can hard code these utxos that get passed in to the `utxos` option, no need to use `getUtxos` or `forcedUtxos`, see [this example](https://github.com/go-faast/coin-payments/blob/master/packages/bitcoin-payments/test/e2e.mainnet.test.ts#L341))
- Have outputs large enough to warrant using all the utxos, while also having enough change leftover to create more than one change output. For example, if all inputs were 0.1 BTC, and the tx had two outputs of 0.1 and 0.15 BTC, then 0.05 BTC change could get split up across 3 change outputs without going under the default 0.01 min change setting.
- Distribute change to multiple addresses not already used as inputs to make sure that the `changeAddress` as an array feature works

Note: To make sure the signed transaction is reproducible, you'll probably have to sort `tbc.inputUtxos` after `selectFromAvailableUtxos` method picks them. The selection process is shuffled so the order will be random in each test run, sorting after selection will make it deterministic.

2021-06-16 15:36 UTC, dzdidi commented on packages/bitcoin-payments/test/e2e.testnet.test.ts
>      const signedTx = await hotWalletPayments.signTransaction(unsignedTx)
I think that assertions should be sufficient now. Please have a look now

2021-06-16 16:23 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        .filter((utxo) => !params.enforcedUtxos.map((u) => `${u.txid}${u.vout}`).includes(`${utxo.txid}${utxo.vout}`)),
This map & include approach would be more concisely expressed as `!params.enforceUtxos.find((u) => u.txid === utxo.txid && u.vout === utxo.vout)`

2021-06-16 16:23 UTC, dylanseago commented on packages/bitcoin-payments/test/e2e.testnet.test.ts
>      const signedTx = await hotWalletPayments.signTransaction(unsignedTx)
@dzdidi This is better, but I'd still like to see the signed tx hash and hex explicitly checked against an expected result. And to be able to validate on a blockchain explorer that the signed tx is valid, was confirmed, and inputs/outputs all as expected. There's the possibility that an incorrect raw transaction is produced due to a bug in the signing logic or psbt building logic. The current assertions have no way to detect such a situation because they only check the auxiliary fields

2021-06-16 19:23 UTC, dylanseago reviewed
Looks good for bitcoin-payments. However please run tests for all packages, I've noticed several type errors introduced by changes to the common interfaces. They should all be relatively trivial to resolve

2021-06-17 14:59 UTC, dylanseago commented
I'm still seeing test failures in other packages. For example:
```
  ● e2e mainnet › create send transaction to an index

    expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 1

    @@ -2,10 +2,11 @@
        Object {
          "address": "bitcoincash:qqyqaklgadws70sc3wa6rrrk2wlpt6tnjuvyll86mu",
          "coinbase": false,
          "satoshis": 3000000,
          "scriptPubKeyHex": "76a914080edbe8eb5d0f3e188bbba18c7653be15e9739788ac",
    +     "signer": 0,
          "spent": false,
          "txHex": "0100000001950708260ee1b332b1b2aa1687e99ac50d57b98000952e148e87d2b8a03de5dd000000006b4830450221009360e33ad04cdad31d2fa6190fea734db4a5710e1ef1201a21dd5225bf022c5b02204e4193aa847530187ce2085f0599cdeab7de607c96b6bb819c66a31028aa07e2412102bde4216a684b8bc73c8a6666398fb321b921407f0f3cdbf19f1abb01fcd1b983ffffffff02c0c62d00000000001976a914080edbe8eb5d0f3e188bbba18c7653be15e9739788ac97915000000000001976a9147fe0e88cb9f3a6248be40f291ae2a395d16703b388ac00000000",
          "txid": "e7ce2764359de9a624e538a26ef874ff3155dc1d7ec2088df1d26e259ea14ee7",
          "value": "0.03",
          "vout": 0,

      66 |     expected = omit(expected, omitFields)
      67 |   }
    > 68 |   expect(actual).toEqual(expected)
         |                  ^
      69 | }
      70 |
      71 | export function expectEqualWhenTruthy(actual: any, expected: any) {

      at Object.expectEqualOmit (../../common/testUtils.ts:68:18)
      at Object.<anonymous> (test/e2e.mainnet.test.ts:238:5)

  ● e2e mainnet › getTransactionInfo › get multi output send

    expect(received).toBe(expected) // Object.is equality

    Expected: "0.07534328"
    Received: "0.07533217"

      291 |     it('get multi output send', async () => {
      292 |       const tx = await payments.getTransactionInfo('3909748b7180634861df44c61bf17c0c0509c87dfb33dc9442639cc4eb97939c')
    > 293 |       expect(tx.amount).toBe('0.07534328')
          |                         ^
      294 |       expect(tx.externalOutputs).toEqual([
      295 |         {
      296 |           address: 'bitcoincash:pzputkzlp6vm05sqkc47tz8ql6pfm2wzpsycz64tvn',

      at Object.<anonymous> (test/e2e.mainnet.test.ts:293:25)
```

2021-06-17 17:49 UTC, dzdidi commented
my bad, have not set mainnet keys at first place and have not done since....

2021-06-18 06:29 UTC, dzdidi commented
@dylanseago , all green now:
```
lerna success run Ran npm script 'test' in 10 packages in 115.7s:
lerna success - @faast/bitcoin-cash-payments
lerna success - @faast/bitcoin-payments
lerna success - @faast/coin-payments
lerna success - @faast/doge-payments
lerna success - @faast/ethereum-payments
lerna success - @faast/litecoin-payments
lerna success - @faast/payments-common
lerna success - @faast/ripple-payments
lerna success - @faast/stellar-payments
lerna success - @faast/tron-payments
```

2021-06-18 13:30 UTC, dylanseago approved these changes

2021-06-21 09:17 UTC, merged